title: May'Log
name: "May's Tech Blog"
author: May 
#twitter_username: lilianweng
baseurl: "/may-log"
description: Document my learning notes.
profile_url: "http://mayaaaa.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
